dataformCoreVersion: 3.0.2
defaultProject: benjaminwestern-test-dataform
defaultLocation: US
defaultDataset: dataform
defaultAssertionDataset: assertions
vars:
  INPUT_BUCKET_1: "input-bucket-1-benjaminwestern-test-dataform"
