config {
  type: "view",
  schema: "intermediate",
  name: "v_users",
  description: "Cleaned version of stackoverflow.users table",
  dependencies: [{
    dataset: "stackoverflow",
    name: "users"
  }, ]
}


SELECT
  ID                                                                     AS USER_ID
  , AGE
  , REATION_DATE
  , ROUND(TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), CREATION_DATE, DAY) / 365) AS USER_TENURE
FROM
  ${ref("users")}
  TABLESAMPLE SYSTEM (10 PERCENT)
LIMIT 100
